//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable CS8981
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace PgBackupRestoreTool
{
    partial class frmMain
    {
        private IContainer components = null;

        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            // --------- 主分區 ---------
            groupBoxConnection = new GroupBox();
            labelConnectionString = new Label();
            comboBoxHost = new ComboBox();
            buttonConnect = new Button();

            groupBoxBackup = new GroupBox();
            labelBackupFile = new Label();
            textBoxBackupFile = new TextBox();
            buttonBrowseBackup = new Button();
            radioBackupPlain = new RadioButton();
            radioBackupCustom = new RadioButton();
            buttonBackup = new Button();

            groupBoxRestore = new GroupBox();
            labelRestoreFile = new Label();
            textBoxRestoreFile = new TextBox();
            buttonBrowseRestore = new Button();
            radioRestorePlain = new RadioButton();
            radioRestoreCustom = new RadioButton();
            labelSchema = new Label();
            comboBoxSchema = new ComboBox();
            checkBoxClean = new CheckBox();
            checkBoxDrop = new CheckBox();
            buttonRestore = new Button();
            ButtonKillSessions = new Button();

            richTextBoxLog = new RichTextBox();

            // --------- 底部 Panel（ProgressBar + Abort）---------
            panelStatus = new Panel();
            progressBar1 = new ProgressBar();
            buttonAbort = new Button();

            SuspendLayout();

            // ========== groupBoxConnection ==========
            groupBoxConnection.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            groupBoxConnection.Controls.Add(labelConnectionString);
            groupBoxConnection.Controls.Add(comboBoxHost);
            groupBoxConnection.Controls.Add(buttonConnect);
            groupBoxConnection.Location = new Point(10, 10);
            groupBoxConnection.Name = "groupBoxConnection";
            groupBoxConnection.Size = new Size(879, 72);
            groupBoxConnection.TabIndex = 0;
            groupBoxConnection.TabStop = false;
            groupBoxConnection.Text = "Connection";

            labelConnectionString.AutoSize = true;
            labelConnectionString.Location = new Point(10, 30);
            labelConnectionString.Name = "labelConnectionString";
            labelConnectionString.Size = new Size(104, 15);
            labelConnectionString.Text = "Connection string:";

            comboBoxHost.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            comboBoxHost.Location = new Point(120, 27);
            comboBoxHost.Name = "comboBoxHost";
            comboBoxHost.Size = new Size(647, 23);

            buttonConnect.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonConnect.Location = new Point(775, 25);
            buttonConnect.Name = "buttonConnect";
            buttonConnect.Size = new Size(90, 27);
            buttonConnect.Text = "Connect";
            buttonConnect.UseVisualStyleBackColor = true;
            buttonConnect.Click += buttonConnect_Click;

            // ========== groupBoxBackup ==========
            groupBoxBackup.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            groupBoxBackup.Controls.Add(labelBackupFile);
            groupBoxBackup.Controls.Add(textBoxBackupFile);
            groupBoxBackup.Controls.Add(buttonBrowseBackup);
            groupBoxBackup.Controls.Add(radioBackupPlain);
            groupBoxBackup.Controls.Add(radioBackupCustom);
            groupBoxBackup.Controls.Add(buttonBackup);
            groupBoxBackup.Enabled = false;
            groupBoxBackup.Location = new Point(10, 90);
            groupBoxBackup.Name = "groupBoxBackup";
            groupBoxBackup.Size = new Size(879, 120);
            groupBoxBackup.TabStop = false;
            groupBoxBackup.Text = "Backup";

            labelBackupFile.AutoSize = true;
            labelBackupFile.Location = new Point(10, 34);
            labelBackupFile.Text = "Backup file:";

            textBoxBackupFile.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            textBoxBackupFile.Location = new Point(120, 30);
            textBoxBackupFile.Size = new Size(647, 23);

            buttonBrowseBackup.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonBrowseBackup.Location = new Point(775, 28);
            buttonBrowseBackup.Size = new Size(90, 27);
            buttonBrowseBackup.Text = "Browse...";
            buttonBrowseBackup.UseVisualStyleBackColor = true;
            buttonBrowseBackup.Click += ButtonBrowseBackup_Click;

            radioBackupPlain.AutoSize = true;
            radioBackupPlain.Checked = true;
            radioBackupPlain.Location = new Point(155, 77);
            radioBackupPlain.Text = "Plain SQL (.sql)";

            radioBackupCustom.AutoSize = true;
            radioBackupCustom.Location = new Point(301, 77);
            radioBackupCustom.Text = "Custom format (-F c)";

            buttonBackup.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonBackup.Location = new Point(775, 71);
            buttonBackup.Size = new Size(90, 30);
            buttonBackup.Text = "Backup";
            buttonBackup.UseVisualStyleBackColor = true;
            buttonBackup.Click += ButtonBackup_Click;

            // ========== groupBoxRestore ==========
            groupBoxRestore.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            groupBoxRestore.Controls.Add(ButtonKillSessions);
            groupBoxRestore.Controls.Add(checkBoxDrop);
            groupBoxRestore.Controls.Add(labelRestoreFile);
            groupBoxRestore.Controls.Add(textBoxRestoreFile);
            groupBoxRestore.Controls.Add(buttonBrowseRestore);
            groupBoxRestore.Controls.Add(radioRestorePlain);
            groupBoxRestore.Controls.Add(radioRestoreCustom);
            groupBoxRestore.Controls.Add(labelSchema);
            groupBoxRestore.Controls.Add(comboBoxSchema);
            groupBoxRestore.Controls.Add(checkBoxClean);
            groupBoxRestore.Controls.Add(buttonRestore);
            groupBoxRestore.Enabled = false;
            groupBoxRestore.Location = new Point(10, 216);
            groupBoxRestore.Name = "groupBoxRestore";
            groupBoxRestore.Size = new Size(879, 180);
            groupBoxRestore.TabStop = false;
            groupBoxRestore.Text = "Restore";

            labelRestoreFile.AutoSize = true;
            labelRestoreFile.Location = new Point(10, 33);
            labelRestoreFile.Text = "Backup file:";

            textBoxRestoreFile.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            textBoxRestoreFile.Location = new Point(120, 30);
            textBoxRestoreFile.Size = new Size(647, 23);

            buttonBrowseRestore.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonBrowseRestore.Location = new Point(775, 28);
            buttonBrowseRestore.Size = new Size(90, 27);
            buttonBrowseRestore.Text = "Browse...";
            buttonBrowseRestore.UseVisualStyleBackColor = true;
            buttonBrowseRestore.Click += ButtonBrowseRestore_Click;

            radioRestorePlain.AutoSize = true;
            radioRestorePlain.Checked = true;
            radioRestorePlain.Location = new Point(155, 66);
            radioRestorePlain.Text = "Plain SQL (.sql)";

            radioRestoreCustom.AutoSize = true;
            radioRestoreCustom.Location = new Point(301, 66);
            radioRestoreCustom.Text = "Custom format (-F c)";

            labelSchema.AutoSize = true;
            labelSchema.Location = new Point(10, 103);
            labelSchema.Text = "Schema:";

            comboBoxSchema.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            comboBoxSchema.DropDownStyle = ComboBoxStyle.DropDownList;
            comboBoxSchema.Enabled = false;
            comboBoxSchema.Location = new Point(120, 100);
            comboBoxSchema.Size = new Size(647, 23);
            comboBoxSchema.SelectedIndexChanged += ComboBoxSchema_SelectedIndexChanged;

            checkBoxClean.AutoSize = true;
            checkBoxClean.Enabled = false;
            checkBoxClean.Location = new Point(120, 146);
            checkBoxClean.Text = "Clean schema before restore";
            checkBoxClean.CheckedChanged += CheckBoxMutualExclusive;

            checkBoxDrop.AutoSize = true;
            checkBoxDrop.Enabled = false;
            checkBoxDrop.Location = new Point(301, 146);
            checkBoxDrop.Text = "Drop schema before restore";
            checkBoxDrop.CheckedChanged += CheckBoxMutualExclusive;

            buttonRestore.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonRestore.Location = new Point(775, 139);
            buttonRestore.Size = new Size(90, 30);
            buttonRestore.Text = "Restore";
            buttonRestore.UseVisualStyleBackColor = true;
            buttonRestore.Click += ButtonRestore_Click;

            ButtonKillSessions.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            ButtonKillSessions.Location = new Point(775, 97);
            ButtonKillSessions.Size = new Size(90, 30);
            ButtonKillSessions.Text = "Terminate";
            ButtonKillSessions.UseVisualStyleBackColor = true;
            ButtonKillSessions.Click += ButtonKillSessions_Click;

            // ========== richTextBoxLog ==========
            richTextBoxLog.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            richTextBoxLog.Location = new Point(10, 402);
            richTextBoxLog.Name = "richTextBoxLog";
            richTextBoxLog.ReadOnly = true;
            richTextBoxLog.Size = new Size(879, 200);
            richTextBoxLog.WordWrap = false;

            // ========== panelStatus ==========
            panelStatus.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            panelStatus.Location = new Point(10, 607);
            panelStatus.Name = "panelStatus";
            panelStatus.Size = new Size(879, 35);

            // progressBar1
            progressBar1.Dock = DockStyle.Fill;
            progressBar1.Name = "progressBar1";

            // buttonAbort
            buttonAbort.Dock = DockStyle.Right;
            buttonAbort.Enabled = false;
            buttonAbort.Name = "buttonAbort";
            buttonAbort.Size = new Size(100, 35);
            buttonAbort.Text = "Abort";
            buttonAbort.UseVisualStyleBackColor = true;
            buttonAbort.Click += buttonAbort_Click;

            panelStatus.Controls.Add(progressBar1);
            panelStatus.Controls.Add(buttonAbort);

            // ========== frmMain ==========
            AutoScaleMode = AutoScaleMode.None;
            ClientSize = new Size(900, 652);
            Controls.Add(panelStatus);
            Controls.Add(richTextBoxLog);
            Controls.Add(groupBoxRestore);
            Controls.Add(groupBoxBackup);
            Controls.Add(groupBoxConnection);
            FormBorderStyle = FormBorderStyle.Sizable;
            MaximizeBox = true;
            Name = "frmMain";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "PostgreSQL Backup/Restore Tool";

            ResumeLayout(false);
        }
        #endregion

        private GroupBox groupBoxConnection;
        private Label labelConnectionString;
        private ComboBox comboBoxHost;
        private Button buttonConnect;

        private GroupBox groupBoxBackup;
        private Label labelBackupFile;
        private TextBox textBoxBackupFile;
        private Button buttonBrowseBackup;
        private RadioButton radioBackupPlain;
        private RadioButton radioBackupCustom;
        private Button buttonBackup;

        private GroupBox groupBoxRestore;
        private Label labelRestoreFile;
        private TextBox textBoxRestoreFile;
        private Button buttonBrowseRestore;
        private RadioButton radioRestorePlain;
        private RadioButton radioRestoreCustom;
        private Label labelSchema;
        private ComboBox comboBoxSchema;
        private CheckBox checkBoxClean;
        private CheckBox checkBoxDrop;
        private Button buttonRestore;
        private Button ButtonKillSessions;

        private RichTextBox richTextBoxLog;

        private Panel panelStatus;
        private ProgressBar progressBar1;
        private Button buttonAbort;
    }
}
