//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable CS8981
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace PgBackupRestoreTool
{
    partial class frmMain
    {
        private IContainer components = null;

        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            groupBoxConnection = new GroupBox();
            labelConnectionString = new Label();
            comboBoxHost = new ComboBox();
            buttonConnect = new Button();
            groupBoxBackup = new GroupBox();
            labelBackupFile = new Label();
            textBoxBackupFile = new TextBox();
            buttonBrowseBackup = new Button();
            radioBackupPlain = new RadioButton();
            radioBackupCustom = new RadioButton();
            buttonBackup = new Button();
            groupBoxRestore = new GroupBox();
            ButtonKillSessions = new Button();
            checkBoxDrop = new CheckBox();
            labelRestoreFile = new Label();
            textBoxRestoreFile = new TextBox();
            buttonBrowseRestore = new Button();
            radioRestorePlain = new RadioButton();
            radioRestoreCustom = new RadioButton();
            labelSchema = new Label();
            comboBoxSchema = new ComboBox();
            checkBoxClean = new CheckBox();
            buttonRestore = new Button();
            richTextBoxLog = new RichTextBox();
            tableLayoutPanelStatus = new TableLayoutPanel();
            progressBar1 = new ProgressBar();
            buttonAbort = new Button();
            groupBoxConnection.SuspendLayout();
            groupBoxBackup.SuspendLayout();
            groupBoxRestore.SuspendLayout();
            tableLayoutPanelStatus.SuspendLayout();
            SuspendLayout();
            // 
            // groupBoxConnection
            // 
            groupBoxConnection.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            groupBoxConnection.Controls.Add(labelConnectionString);
            groupBoxConnection.Controls.Add(comboBoxHost);
            groupBoxConnection.Controls.Add(buttonConnect);
            groupBoxConnection.Location = new Point(10, 10);
            groupBoxConnection.Name = "groupBoxConnection";
            groupBoxConnection.Size = new Size(879, 72);
            groupBoxConnection.TabIndex = 0;
            groupBoxConnection.TabStop = false;
            groupBoxConnection.Text = "Connection";
            // 
            // labelConnectionString
            // 
            labelConnectionString.AutoSize = true;
            labelConnectionString.Location = new Point(10, 30);
            labelConnectionString.Name = "labelConnectionString";
            labelConnectionString.Size = new Size(104, 15);
            labelConnectionString.TabIndex = 0;
            labelConnectionString.Text = "Connection string:";
            // 
            // comboBoxHost
            // 
            comboBoxHost.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            comboBoxHost.Location = new Point(120, 27);
            comboBoxHost.Name = "comboBoxHost";
            comboBoxHost.Size = new Size(653, 23);
            comboBoxHost.TabIndex = 1;
            // 
            // buttonConnect
            // 
            buttonConnect.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonConnect.Location = new Point(779, 25);
            buttonConnect.Name = "buttonConnect";
            buttonConnect.Size = new Size(90, 27);
            buttonConnect.TabIndex = 2;
            buttonConnect.Text = "Connect";
            buttonConnect.UseVisualStyleBackColor = true;
            buttonConnect.Click += buttonConnect_Click;
            // 
            // groupBoxBackup
            // 
            groupBoxBackup.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            groupBoxBackup.Controls.Add(labelBackupFile);
            groupBoxBackup.Controls.Add(textBoxBackupFile);
            groupBoxBackup.Controls.Add(buttonBrowseBackup);
            groupBoxBackup.Controls.Add(radioBackupPlain);
            groupBoxBackup.Controls.Add(radioBackupCustom);
            groupBoxBackup.Controls.Add(buttonBackup);
            groupBoxBackup.Enabled = false;
            groupBoxBackup.Location = new Point(10, 90);
            groupBoxBackup.Name = "groupBoxBackup";
            groupBoxBackup.Size = new Size(879, 120);
            groupBoxBackup.TabIndex = 3;
            groupBoxBackup.TabStop = false;
            groupBoxBackup.Text = "Backup";
            // 
            // labelBackupFile
            // 
            labelBackupFile.AutoSize = true;
            labelBackupFile.Location = new Point(10, 34);
            labelBackupFile.Name = "labelBackupFile";
            labelBackupFile.Size = new Size(68, 15);
            labelBackupFile.TabIndex = 0;
            labelBackupFile.Text = "Backup file:";
            // 
            // textBoxBackupFile
            // 
            textBoxBackupFile.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            textBoxBackupFile.Location = new Point(120, 30);
            textBoxBackupFile.Name = "textBoxBackupFile";
            textBoxBackupFile.Size = new Size(653, 23);
            textBoxBackupFile.TabIndex = 1;
            // 
            // buttonBrowseBackup
            // 
            buttonBrowseBackup.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonBrowseBackup.Location = new Point(779, 28);
            buttonBrowseBackup.Name = "buttonBrowseBackup";
            buttonBrowseBackup.Size = new Size(90, 27);
            buttonBrowseBackup.TabIndex = 2;
            buttonBrowseBackup.Text = "Browse...";
            buttonBrowseBackup.UseVisualStyleBackColor = true;
            buttonBrowseBackup.Click += ButtonBrowseBackup_Click;
            // 
            // radioBackupPlain
            // 
            radioBackupPlain.AutoSize = true;
            radioBackupPlain.Checked = true;
            radioBackupPlain.Location = new Point(155, 77);
            radioBackupPlain.Name = "radioBackupPlain";
            radioBackupPlain.Size = new Size(104, 19);
            radioBackupPlain.TabIndex = 3;
            radioBackupPlain.TabStop = true;
            radioBackupPlain.Text = "Plain SQL (.sql)";
            // 
            // radioBackupCustom
            // 
            radioBackupCustom.AutoSize = true;
            radioBackupCustom.Location = new Point(301, 77);
            radioBackupCustom.Name = "radioBackupCustom";
            radioBackupCustom.Size = new Size(134, 19);
            radioBackupCustom.TabIndex = 4;
            radioBackupCustom.Text = "Custom format (-F c)";
            // 
            // buttonBackup
            // 
            buttonBackup.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonBackup.Location = new Point(779, 71);
            buttonBackup.Name = "buttonBackup";
            buttonBackup.Size = new Size(90, 30);
            buttonBackup.TabIndex = 5;
            buttonBackup.Text = "Backup";
            buttonBackup.UseVisualStyleBackColor = true;
            buttonBackup.Click += ButtonBackup_Click;
            // 
            // groupBoxRestore
            // 
            groupBoxRestore.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            groupBoxRestore.Controls.Add(ButtonKillSessions);
            groupBoxRestore.Controls.Add(checkBoxDrop);
            groupBoxRestore.Controls.Add(labelRestoreFile);
            groupBoxRestore.Controls.Add(textBoxRestoreFile);
            groupBoxRestore.Controls.Add(buttonBrowseRestore);
            groupBoxRestore.Controls.Add(radioRestorePlain);
            groupBoxRestore.Controls.Add(radioRestoreCustom);
            groupBoxRestore.Controls.Add(labelSchema);
            groupBoxRestore.Controls.Add(comboBoxSchema);
            groupBoxRestore.Controls.Add(checkBoxClean);
            groupBoxRestore.Controls.Add(buttonRestore);
            groupBoxRestore.Enabled = false;
            groupBoxRestore.Location = new Point(10, 216);
            groupBoxRestore.Name = "groupBoxRestore";
            groupBoxRestore.Size = new Size(879, 180);
            groupBoxRestore.TabIndex = 2;
            groupBoxRestore.TabStop = false;
            groupBoxRestore.Text = "Restore";
            // 
            // ButtonKillSessions
            // 
            ButtonKillSessions.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            ButtonKillSessions.Location = new Point(779, 97);
            ButtonKillSessions.Name = "ButtonKillSessions";
            ButtonKillSessions.Size = new Size(90, 30);
            ButtonKillSessions.TabIndex = 0;
            ButtonKillSessions.Text = "Terminate";
            ButtonKillSessions.UseVisualStyleBackColor = true;
            ButtonKillSessions.Click += ButtonKillSessions_Click;
            // 
            // checkBoxDrop
            // 
            checkBoxDrop.AutoSize = true;
            checkBoxDrop.Enabled = false;
            checkBoxDrop.Location = new Point(301, 146);
            checkBoxDrop.Name = "checkBoxDrop";
            checkBoxDrop.Size = new Size(171, 19);
            checkBoxDrop.TabIndex = 1;
            checkBoxDrop.Text = "Drop schema before restore";
            checkBoxDrop.CheckedChanged += CheckBoxMutualExclusive;
            // 
            // labelRestoreFile
            // 
            labelRestoreFile.AutoSize = true;
            labelRestoreFile.Location = new Point(10, 33);
            labelRestoreFile.Name = "labelRestoreFile";
            labelRestoreFile.Size = new Size(68, 15);
            labelRestoreFile.TabIndex = 2;
            labelRestoreFile.Text = "Backup file:";
            // 
            // textBoxRestoreFile
            // 
            textBoxRestoreFile.AllowDrop = true;
            textBoxRestoreFile.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            textBoxRestoreFile.Location = new Point(120, 30);
            textBoxRestoreFile.Name = "textBoxRestoreFile";
            textBoxRestoreFile.Size = new Size(653, 23);
            textBoxRestoreFile.TabIndex = 3;
            textBoxRestoreFile.DragDrop += textBoxRestoreFile_DragDrop;
            textBoxRestoreFile.DragEnter += textBoxRestoreFile_DragEnter;
            // 
            // buttonBrowseRestore
            // 
            buttonBrowseRestore.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonBrowseRestore.Location = new Point(779, 28);
            buttonBrowseRestore.Name = "buttonBrowseRestore";
            buttonBrowseRestore.Size = new Size(90, 27);
            buttonBrowseRestore.TabIndex = 4;
            buttonBrowseRestore.Text = "Browse...";
            buttonBrowseRestore.UseVisualStyleBackColor = true;
            buttonBrowseRestore.Click += ButtonBrowseRestore_Click;
            // 
            // radioRestorePlain
            // 
            radioRestorePlain.AutoSize = true;
            radioRestorePlain.Checked = true;
            radioRestorePlain.Location = new Point(155, 66);
            radioRestorePlain.Name = "radioRestorePlain";
            radioRestorePlain.Size = new Size(104, 19);
            radioRestorePlain.TabIndex = 5;
            radioRestorePlain.TabStop = true;
            radioRestorePlain.Text = "Plain SQL (.sql)";
            // 
            // radioRestoreCustom
            // 
            radioRestoreCustom.AutoSize = true;
            radioRestoreCustom.Location = new Point(301, 66);
            radioRestoreCustom.Name = "radioRestoreCustom";
            radioRestoreCustom.Size = new Size(134, 19);
            radioRestoreCustom.TabIndex = 6;
            radioRestoreCustom.Text = "Custom format (-F c)";
            // 
            // labelSchema
            // 
            labelSchema.AutoSize = true;
            labelSchema.Location = new Point(10, 103);
            labelSchema.Name = "labelSchema";
            labelSchema.Size = new Size(51, 15);
            labelSchema.TabIndex = 7;
            labelSchema.Text = "Schema:";
            // 
            // comboBoxSchema
            // 
            comboBoxSchema.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            comboBoxSchema.DropDownStyle = ComboBoxStyle.DropDownList;
            comboBoxSchema.Enabled = false;
            comboBoxSchema.Location = new Point(120, 100);
            comboBoxSchema.Name = "comboBoxSchema";
            comboBoxSchema.Size = new Size(653, 23);
            comboBoxSchema.TabIndex = 8;
            comboBoxSchema.SelectedIndexChanged += ComboBoxSchema_SelectedIndexChanged;
            // 
            // checkBoxClean
            // 
            checkBoxClean.AutoSize = true;
            checkBoxClean.Enabled = false;
            checkBoxClean.Location = new Point(120, 146);
            checkBoxClean.Name = "checkBoxClean";
            checkBoxClean.Size = new Size(174, 19);
            checkBoxClean.TabIndex = 9;
            checkBoxClean.Text = "Clean schema before restore";
            checkBoxClean.CheckedChanged += CheckBoxMutualExclusive;
            // 
            // buttonRestore
            // 
            buttonRestore.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonRestore.Location = new Point(779, 139);
            buttonRestore.Name = "buttonRestore";
            buttonRestore.Size = new Size(90, 30);
            buttonRestore.TabIndex = 10;
            buttonRestore.Text = "Restore";
            buttonRestore.UseVisualStyleBackColor = true;
            buttonRestore.Click += ButtonRestore_Click;
            // 
            // richTextBoxLog
            // 
            richTextBoxLog.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            richTextBoxLog.Location = new Point(10, 402);
            richTextBoxLog.Name = "richTextBoxLog";
            richTextBoxLog.ReadOnly = true;
            richTextBoxLog.Size = new Size(879, 200);
            richTextBoxLog.TabIndex = 1;
            richTextBoxLog.Text = "";
            richTextBoxLog.WordWrap = false;
            // 
            // tableLayoutPanelStatus
            // 
            tableLayoutPanelStatus.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tableLayoutPanelStatus.ColumnCount = 2;
            tableLayoutPanelStatus.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            tableLayoutPanelStatus.ColumnStyles.Add(new ColumnStyle());
            tableLayoutPanelStatus.Controls.Add(progressBar1, 0, 0);
            tableLayoutPanelStatus.Controls.Add(buttonAbort, 1, 0);
            tableLayoutPanelStatus.Location = new Point(10, 607);
            tableLayoutPanelStatus.Name = "tableLayoutPanelStatus";
            tableLayoutPanelStatus.RowCount = 1;
            tableLayoutPanelStatus.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tableLayoutPanelStatus.Size = new Size(879, 35);
            tableLayoutPanelStatus.TabIndex = 0;
            // 
            // progressBar1
            // 
            progressBar1.Dock = DockStyle.Fill;
            progressBar1.Location = new Point(3, 3);
            progressBar1.Name = "progressBar1";
            progressBar1.Size = new Size(777, 29);
            progressBar1.TabIndex = 0;
            // 
            // buttonAbort
            // 
            buttonAbort.Anchor = AnchorStyles.Right;
            buttonAbort.Enabled = false;
            buttonAbort.Location = new Point(786, 3);
            buttonAbort.Name = "buttonAbort";
            buttonAbort.Size = new Size(90, 29);
            buttonAbort.TabIndex = 1;
            buttonAbort.Text = "Abort";
            buttonAbort.UseVisualStyleBackColor = true;
            buttonAbort.Click += buttonAbort_Click;
            // 
            // frmMain
            // 
            AutoScaleMode = AutoScaleMode.None;
            ClientSize = new Size(900, 652);
            Controls.Add(tableLayoutPanelStatus);
            Controls.Add(richTextBoxLog);
            Controls.Add(groupBoxRestore);
            Controls.Add(groupBoxBackup);
            Controls.Add(groupBoxConnection);
            Name = "frmMain";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "PostgreSQL Backup/Restore Tool";
            groupBoxConnection.ResumeLayout(false);
            groupBoxConnection.PerformLayout();
            groupBoxBackup.ResumeLayout(false);
            groupBoxBackup.PerformLayout();
            groupBoxRestore.ResumeLayout(false);
            groupBoxRestore.PerformLayout();
            tableLayoutPanelStatus.ResumeLayout(false);
            ResumeLayout(false);
        }
        #endregion

        private GroupBox groupBoxConnection;
        private Label labelConnectionString;
        private ComboBox comboBoxHost;
        private Button buttonConnect;

        private GroupBox groupBoxBackup;
        private Label labelBackupFile;
        private TextBox textBoxBackupFile;
        private Button buttonBrowseBackup;
        private RadioButton radioBackupPlain;
        private RadioButton radioBackupCustom;
        private Button buttonBackup;

        private GroupBox groupBoxRestore;
        private Label labelRestoreFile;
        private TextBox textBoxRestoreFile;
        private Button buttonBrowseRestore;
        private RadioButton radioRestorePlain;
        private RadioButton radioRestoreCustom;
        private Label labelSchema;
        private ComboBox comboBoxSchema;
        private CheckBox checkBoxClean;
        private CheckBox checkBoxDrop;
        private Button buttonRestore;
        private Button ButtonKillSessions;

        private RichTextBox richTextBoxLog;

        private TableLayoutPanel tableLayoutPanelStatus;
        private ProgressBar progressBar1;
        private Button buttonAbort;
    }
}
